robot:
  chassis:
    length_cm: 20
    width_cm: 12
    wheelbase_cm: 14
  drive_type: "caster"
  sensors:
    - name: "Front"
      mount: [0.00, -0.48]
      angle: 0
      range: 200
      sweep: 30
    - name: "Left"
      mount: [-0.50, 0.00]
      angle: -90
      range: 200
      sweep: 30
    - name: "Right"
      mount: [0.50, 0.00]
      angle: 90
      range: 200
      sweep: 30
    - name: "Rear"
      mount: [0.00, 0.48]
      angle: 180
      range: 150
      sweep: 30
  ir_sensors:
    - name: "IR Front-left"
      mount: [-0.35, -0.48]
      threshold: 500
    - name: "IR Front-right"
      mount: [0.35, -0.48]
      threshold: 500
